name: novu_notifications_flutter
description: A Flutter app for Novu notifications integration.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
