name: E2E API Tests

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      ee:
        description: 'use the ee version of api'
        required: false
        default: false
        type: boolean

jobs:
  e2e_api:
    name: Test E2E
    runs-on: blacksmith-8vcpu-ubuntu-2404
    timeout-minutes: 30
    permissions:
      contents: read
      deployments: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout with submodules
        if: ${{ inputs.ee }}
        with:
          submodules: true
          token: ${{ secrets.SUBMODULES_TOKEN }}

      # Else checkout without submodules if the token is not provided
      - uses: actions/checkout@v4
        name: Checkout
        if: ${{ !inputs.ee }}

      - uses: ./.github/actions/setup-project
        name: Setup project
        with:
          submodules: ${{ inputs.ee }}

      - uses: ./.github/actions/start-localstack
        name: Start localstack

      - name: Build API & Worker
        run: CI='' pnpm nx run-many --skip-nx-cache --target=build --all --projects=@novu/api-service,@novu/worker

      - name: Start Worker
        shell: bash
        env:
          NOVU_ENTERPRISE: ${{ inputs.ee }}
        run: |
          # Start the worker service in the background
          pnpm start:worker:test 2>&1 &

          # Get the PID of the last background command
          WORKER_PID=$!

          # Start a background process to monitor the worker service. This ensures that the worker service is restarted if it stops in the CI environment
          (
            while true; do
              # Check if the worker service is running
              if ! kill -0 $WORKER_PID 2> /dev/null; then
                echo "Worker service has stopped. Restarting..."
                pnpm start:test 2>&1 &
                WORKER_PID=$!
              fi
              sleep 1 # Check every 1 second
            done
          ) &

      - name: Wait on worker
        shell: bash
        run: wait-on --timeout=180000 http://127.0.0.1:1342/v1/health-check

      - name: Run Novu V1 E2E tests
        if: ${{ !inputs.ee }}
        run: |
          pnpm --filter @novu/api-service test:e2e:novu-v0

      - name: Run Novu V2 E2E tests
        if: ${{ inputs.ee }}
        run: |
          pnpm --filter @novu/api-service test:e2e:novu-v2
